[programs]
elixir_1_13 = {}
postgresql_14 = {}
nodejs = {}

[hooks]

postShellHook = '''
echo "$PWD"
export LANG=C.UTF-8
# keep your shell history in iex
export ERL_AFLAGS="-kernel shell_history enabled"


export PGDATA=$PWD/postgres_data
export PGHOST=$PWD/postgres 
export LOG_PATH=$PWD/postgres/LOG
export PGDATABASE=postgres
export DATABASE_URL="postgresql:///postgres?host=$PGHOST"
if [ ! -d $PWD/postgres ]; then
mkdir -p $PWD/postgres
fi
if [ ! -d $PGDATA ]; then
echo 'Initializing postgresql database...'
initdb $PGDATA --auth=trust >/dev/null
fi
pg_ctl start -l $LOG_PATH -o "-p 5435 -c listen_addresses='*' -c unix_socket_directories=$PWD/postgres -c unix_socket_permissions=0700"
#psql -p 5435 postgres -c 'create extension if not exists postgis' || true   
mkdir -p .nix-mix
mkdir -p .nix-hex
export MIX_HOME=$PWD/.nix-mix
export HEX_HOME=$PWD/.nix-hex
export PATH=$MIX_HOME/bin:$PATH
export PATH=$HEX_HOME/bin:$PATH

#EXAMPLE_VAR="foo"
#echo "Hello World"

echo \# Show versions of packages providing binaries with a bit of color
find @DEVSHELL_DIR@/bin -exec realpath {} \; | \
    cut -d- -f2- | cut -d/ -f1 | sort -u | \
    grep -P --colour=always '(?:^|(?<=[-]))[0-9.]*|$'
echo
'''

