name: "Update Index"

on:
  workflow_dispatch:
  
concurrency: 
  group: flake-update
  cancel-in-progress: true

jobs:
  update_inputs:
    name: "Update and sync index flake"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: master
    - name: "Install nix"
      uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.NIX_GIT_TOKEN }}
    - name: Git Configure
      run: |
          git config --global user.name 'Flox Updater'
          git config --global user.email 'developers@floxdev.com'

          # TODO: import and use flox?
          git config --global url."https://${{ secrets.NIX_GIT_TOKEN }}@github.com".insteadOf ssh://git@github.com

    - name: Update Flake
      run: |
        nix flake update --commit-lock-file --show-trace -vv
        git push
